MurmurationsNetwork/MurmurationsProfileGeneratorV2

- app/root.jsx
- app/routes/index.jsx
- app/utils/fetchGet.js
- app/utils/fetchPost.js
- app/utils/parseRef.js
> Add error handling and catch boundary to data fetching and posting

- app/root.jsx
- app/routes/index.jsx
> refactor: improve catch and error boundaries UI

- app/root.jsx
- app/routes/index.jsx
> feat: create fixed and scrollable sections

- app/components/EnumField.jsx
- app/components/FormField.jsx
- app/components/MultipleFormField.jsx
- app/root.jsx
- app/routes/index.jsx
> fix: control the sizing of the schema instance display

- app/components/EnumField.jsx
- app/components/FormField.jsx
- app/utils/generateForm.js
> feat: group object fields

- app/routes/index.jsx
> feat: show selected schemas at top of data input form

- app/routes/index.jsx
- app/utils/kv.server.js
- app/utils/profile.server.js
- app/utils/session.server.js
- app/utils/user.server.js
> feat: add profiles metadata

- app/routes/index.jsx
- app/routes/profiles/$profileHash.jsx
- app/utils/session.server.js
> feat: create profile JSON route and show schemas

- app/routes/index.jsx
- app/utils/profile.server.js
- docs/mongo.md
> feat: add title to profile

- app/utils/generateForm.jsx
> feat: pass default value in hidden field

- app/routes/index.jsx
> feat: add URL key for schema to load from link

- app/utils/generateForm.jsx
> fix: make keys unique so edit profile functionality re-renders

- app/routes/index.jsx
> fix: handle multiple form field input values

- app/routes/index.jsx
> feat: add delete confirmation modal

- README.md
- app/routes/get-nodes.jsx
> feat: add index viewer

- app/routes/get-nodes.jsx
- app/routes/index.jsx
- app/utils/schema.js
> feat: remove default schema from schema list

- app/routes/get-nodes.jsx
> fix: get-nodes page parameter in pagination is missing

- app/routes/get-nodes.jsx
> fix: fix query params lost when using sort filters

- app/routes/get-nodes.jsx
> fix: fix query params lost when using sort filters (#103)

- app/routes/get-nodes.jsx
> fix: pagination has wrong URL when schema is not "all"

- app/root.jsx
- app/routes/get-nodes.jsx
- app/routes/index.jsx
> feat: add link to get-nodes page

- app/routes/index.jsx
> fix: close delete modal after profile deleted

- app/routes/index.jsx
> fix: improve UX

- app/utils/schema.js
> feat: filter out test schemas

- app/routes/get-nodes.jsx
- app/routes/index.jsx
> feat: add search button transition

- app/routes/index.jsx
- app/routes/login.jsx
> fix: hide profile list during preview

- app/routes/login.jsx
> fix: improve login UX

- app/root.jsx
- app/routes/tools.jsx
- app/utils/index-api.js
> feat: create index tools page
